displayName: X-Request-Start
type: middleware

import: github.com/hitz-group/traefik-copy-auth-header

summary: 'Add the header authorization to request based on apptoken header'

testData:
  name: "transform_auth_header"